name: CI_Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, task0, task00, task1, task01, task2, task02, task3, task03, task5, task05, task6, task06, task7, task07, task8, task08, task9, task09]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install glfw
      run: |
        sudo apt install -y \
          libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules \
          libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
        git submodule update --init -- external/glfw
        cmake -S external/glfw -B external/glfwbuild
        cd external/glfwbuild
        cmake --build . --config Release
        cmake --install . --prefix ../glfwlib

    - name: install eigen
      run: |
        git submodule update --init -- external/eigen

    - name: build
      run: |
        cmake -S . -B build 
        cd build
        cmake --build .